<?php
echo '<header>';
echo '    <div class="header-1">';
echo '        <a href="#" class="fab fa-facebook" style="font-size: 24px"></a>';
echo '        <a href="#" class="fab fa-instagram" style="font-size: 24px"></a>';
echo '    </div>';
echo '    <div class="header-2">';
echo '        <a href="index.php" class="logo"><img src="green_market-logo.png" id="market-name"></a>';
echo '        <div class="searching-container">';
echo '            <form onsubmit="return search()" class="search-bar-container">';
echo '                <input type="text" id="search-bar" placeholder="Search product">';
echo '                <a href="#" class="fas fa-search">';
echo '                </a>';
echo '            </form>';
echo '        </div>';
echo '    </div>';
echo '    <!-- menu bars -->';
echo '    <div class="nav" id="nav-theme">';
echo '        <nav class="navbar py-0 navbar-expand-lg navbar-light">';
echo '            <div class="container-fluid">';
echo '                <a class="navbar-brand" href="#"></a>';
echo '                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">';
echo '                    <span class="navbar-toggler-icon"></span>';
echo '                </button>';
echo '                <div class="collapse navbar-collapse" id="navbarSupportedContent">';
echo '                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 fs-1">';
echo '                        <li class="nav-item">';
echo '                            <a class="nav-link active px-4" aria-current="page" href="index.php">Home</a>';
echo '                        </li>';
echo '                        <li class="nav-item">';
echo '                            <a class="nav-link px-4" href="P2-P3/aisles.html">Aisles</a>';
echo '                        </li>';
echo '                        <li class="nav-item">';
echo '                            <a class="nav-link px-4" href="extra/deals.html">Deals</a>';
echo '                        </li>';
echo '                        <li class="nav-item">';
echo '                            <a class="nav-link px-4" href="extra/services.html">Services</a>';
echo '                        </li>';
echo '                    </ul>';
echo '                    <div class="user-shopping">';
echo '                        <span id="shopping-cart">';
echo '                            <a href="P4/P4-shopping_cart.php" class="fas fa-shopping-cart"></a>';
echo '                        </span>';
echo '                        <span id="user-login">';
echo '                            <a href="P5/P5-login.php" class="fas fa-user"></a>';
echo '                        </span>';
echo '                    </div>';
echo '                </div>';
echo '            </div>';
echo '        </nav>';
echo '    </div>';
echo '</header>';

?>